# Generated by Django 4.1 on 2023-02-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Choose gender"),
                    ("Masculin", "Masculin"),
                    ("Feminin", "Feminin"),
                    ("Autre", "Autre"),
                ],
                max_length=100,
            ),
        ),
    ]
