# Generated by Django 4.1 on 2023-02-28 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agency_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("approuve", "Approuvé"), ("rejete", "Rejeté")],
                        max_length=20,
                    ),
                ),
                ("commentaire", models.TextField()),
                ("date_decision", models.DateTimeField(auto_now_add=True)),
                (
                    "intervenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emprunteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("racine", models.CharField(blank=True, max_length=8, null=True)),
                ("nom", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "emprunteur_type",
                    models.CharField(
                        choices=[("client", "Client"), ("prospect", "Prospect")],
                        default="client",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EtapeDossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etape",
                    models.CharField(
                        choices=[
                            ("gestionnaire", "Chargé d'affaire"),
                            ("chef_agence", "Chef d'agence"),
                            ("chef_zone", "Chef de zone"),
                            ("de", "DE"),
                            ("cic", "CIC"),
                            ("abi", "ABI"),
                            ("bcp", "BCP"),
                        ],
                        default="gestionnaire",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("contenu", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypeCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("date_ajout", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LigneCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.IntegerField()),
                ("commentaire", models.TextField()),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "type_credit",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credit.typecredit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntervenantNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lue", models.BooleanField(default=False)),
                (
                    "date_lue",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "intervenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credit.notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemandeCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_introduction", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "chg_initiateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agency_manager.gestionnaire",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credit.decision",
                    ),
                ),
                (
                    "emprunteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credit.emprunteur",
                    ),
                ),
                (
                    "etape",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="credit.etapedossier",
                    ),
                ),
                (
                    "ligne_credit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credit.lignecredit",
                    ),
                ),
            ],
        ),
    ]
