# Generated by Django 4.1 on 2023-03-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandecredit",
            name="commentaire",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="lignecredit",
            name="commentaire",
            field=models.TextField(max_length=2000),
        ),
    ]
