# Generated by Django 4.1 on 2023-04-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0004_remove_demandecredit_ligne_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandecredit",
            name="etape",
            field=models.CharField(
                choices=[
                    ("gestionnaire", "Chargé d'affaire"),
                    ("chef_agence", "Chef d'agence"),
                    ("chef_zone", "Chef de zone"),
                    ("de", "DE"),
                    ("cic", "CIC"),
                    ("abi", "ABI"),
                    ("bcp", "BCP"),
                ],
                default="gestionnaire",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="EtapeDossier",
        ),
    ]
