# Generated by Django 4.1 on 2023-04-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0005_alter_demandecredit_etape_delete_etapedossier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandecredit",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
    ]
