# Generated by Django 4.1 on 2023-04-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit", "0006_alter_demandecredit_commentaire"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="date",
            new_name="date_envoie",
        ),
        migrations.RemoveField(
            model_name="intervenantnotification",
            name="date_lue",
        ),
        migrations.RemoveField(
            model_name="intervenantnotification",
            name="lue",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="contenu",
        ),
        migrations.AddField(
            model_name="intervenantnotification",
            name="demande_credit",
            field=models.ManyToManyField(to="credit.demandecredit"),
        ),
        migrations.AddField(
            model_name="notification",
            name="date_lue",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="lue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.CharField(default="null", max_length=500),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="intervenantnotification",
            name="notification",
        ),
        migrations.AddField(
            model_name="intervenantnotification",
            name="notification",
            field=models.ManyToManyField(to="credit.notification"),
        ),
    ]
