# Generated by Django 4.1 on 2023-04-11 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credit", "0007_rename_date_notification_date_envoie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervenantnotification",
            name="intervenant",
        ),
        migrations.AddField(
            model_name="intervenantnotification",
            name="intervenant",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
