# Generated by Django 4.1 on 2023-04-13 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("credit", "0008_remove_intervenantnotification_intervenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="demande_credit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="credit.demandecredit",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="destinataire",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_destinataire",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="expediteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications_expediteur",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="IntervenantNotification",
        ),
    ]
